# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspberry',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devices.Device'),
        ),
    ]
