# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0002_auto_20161103_1818'),
        ('devices', '0002_auto_20161001_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspberry',
            name='residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='residences.Residence'),
        ),
    ]
