---
application_name: 'belmis'
application_root: '/hack/belmis/'
application_user: 'hack'

postgresql_version: 9.3
postgresql_encoding: 'UTF-8'
postgresql_locale: 'en_US.UTF-8'
postgresql_cluster_name: 'main'
postgresql_app_user_password: 'f3n5o%vh(xbh_@cbfwyj'


postgresql_databases:
  - name: '{{ application_name }}' 

postgresql_users:
  - name: '{{ application_name }}'
    pass: '{{ postgresql_app_user_password }}'

postgresql_user_privileges:
  - name: '{{ application_name }}'
    db: '{{ application_name }}'


letsencrypt_email: 'n'
letsencrypt_pause_services: 'nginx'
letsencrypt_request_www: 'false'

# Ansistrano deploy settings
ansistrano_git_repo: 'git@github.com:HackSoftware/cookiecutter-django-ansible.git' # Location of the git repository

ansistrano_deploy_via: "git"
ansistrano_keep_releases: 5
ansistrano_deploy_to: '{{ application_root }}'
ansistrano_git_identity_key_path: '~/.ssh/id_rsa'
ansistrano_shared_paths: ['media', 'staticfiles']
ansistrano_shared_files: []
ansistrano_after_cleanup_tasks_file: "{{ playbook_dir }}/deploy_tasks/after-cleanup.yml"

